server:
  host: <hostname>
  mcp_port: <portnumber>
  api_port: <api_portnumber>
  mcp_path: /mcp

azure:
  project_endpoint: indigo-endpoints
  agent_id: agent-id

indigo:
  flight_search_url: <Indigo-website-search-api>
  seat_map_url: <Indigo-seat-search-api>
